"""Alert and trigger layer — SIH PS 26083 requirement R6 (Layer 5).

Three outputs from one decision: machine-readable Heat Action Plan triggers, a
CAP 1.2 XML alert, and a webhook payload preview. All are dry runs. There is no
SMS/WhatsApp gateway, no SACHET connection and no outbound HTTP anywhere in
this module; the schemas (schemas/alerts.py) make that structural rather than
a matter of remembering.

CAP 1.2 is emitted as ONE ``<alert>`` with one ``<info>`` per Heat Action Plan
level among the qualifying zones, so a zone at Orange is never described with
the severity of a zone at Red. ``status`` is always "Draft" and ``certainty``
never "Observed": these are modelled scores (IMPLEMENTATION_PLAN.md §7.2).
"""
from __future__ import annotations

import xml.etree.ElementTree as ET

import pandas as pd

from app.core.errors import NotFoundError
from app.data import registry
from app.schemas.alerts import (
    HapLevel,
    TriggerGroup,
    TriggersResponse,
    WebhookDelivery,
    WebhookPreview,
    WebhookRequest,
)
from app.services import hap, spatial
from app.services.advisory import CAP_SEVERITY, CAP_URGENCY, cap_description
from app.services.frames import DayContext, history_context

CAP_NS = "urn:oasis:names:tc:emergency:cap:1.2"
CAP_SENDER = "heatlens-demo@example.invalid"  # no real sending identity exists


def _decisions(city_id: str, date: str, ctx: DayContext):
    """(RiskZonesResponse, {zone_id: HapDecision}) for one date."""
    payload = spatial.map_payload(city_id, date, ctx)
    t = spatial.city_ta_max(date, ctx)
    return payload, {z.zone_id: hap.decide(t.value_c, z.risk_band, z.health, t.source) for z in payload.zones}


def triggers(city_id: str, date: str, ctx: DayContext | None = None) -> TriggersResponse:
    ctx = ctx or history_context()
    payload, decisions = _decisions(city_id, date, ctx)
    t = spatial.city_ta_max(date, ctx)

    by_level: dict[HapLevel, list[str]] = {}
    for zone_id, decision in decisions.items():
        by_level.setdefault(decision.level, []).append(zone_id)

    ordered = sorted(by_level, key=hap.level_rank, reverse=True)
    groups = [TriggerGroup(level=lv, zone_ids=by_level[lv], actions=hap.actions_for(lv)) for lv in ordered]
    top_basis = next(d.basis for d in decisions.values() if d.level == ordered[0])

    return TriggersResponse(
        city=city_id,
        date=date,
        source=payload.source,
        issued_at=payload.issued_at,
        level_basis=top_basis,
        city_ta_max_c=round(t.value_c, 1),
        city_ta_max_source=t.source,
        groups=groups,
    )


def _sub(parent: ET.Element, tag: str, text: str | None = None) -> ET.Element:
    el = ET.SubElement(parent, f"{{{CAP_NS}}}{tag}")
    if text is not None:
        el.text = text
    return el


def _polygon_text(zone_id: str) -> str:
    return " ".join(f"{lat:.6f},{lon:.6f}" for lat, lon in spatial.zone_polygon_latlon(zone_id))


def cap_xml(
    city_id: str, date: str, ctx: DayContext | None = None, min_level: HapLevel = "Yellow"
) -> str | None:
    """A CAP 1.2 document for every zone at or above ``min_level``, or None if none qualify."""
    ctx = ctx or history_context()
    city = registry.get_city(city_id)
    if city is None:
        raise NotFoundError(f"city {city_id!r} not found")
    payload, decisions = _decisions(city_id, date, ctx)
    risks = {z.zone_id: z for z in payload.zones}

    floor = hap.level_rank(min_level)
    qualifying = [zid for zid, d in decisions.items() if hap.level_rank(d.level) >= floor]
    if not qualifying:
        return None

    by_level: dict[HapLevel, list[str]] = {}
    for zid in qualifying:
        by_level.setdefault(decisions[zid].level, []).append(zid)

    now = pd.Timestamp.now(tz=city.tz)
    day_start = pd.Timestamp(date).tz_localize(city.tz)
    day_end = day_start + pd.Timedelta(days=1) - pd.Timedelta(seconds=1)

    ET.register_namespace("", CAP_NS)
    alert = ET.Element(f"{{{CAP_NS}}}alert")
    _sub(alert, "identifier", f"heatlens-{city_id}-{date}-{now:%Y%m%dT%H%M%S}")
    _sub(alert, "sender", CAP_SENDER)
    _sub(alert, "sent", now.isoformat(timespec="seconds"))
    _sub(alert, "status", "Draft")  # never "Actual": no real alerting authority sits behind this feed
    _sub(alert, "msgType", "Alert")
    _sub(alert, "scope", "Public")
    _sub(
        alert,
        "note",
        "DRAFT generated by the HeatLens dry-run feed. Not an operational alert. "
        "Uncalibrated composite index; mortality figures are published relative risks, not death forecasts.",
    )

    for level in sorted(by_level, key=hap.level_rank, reverse=True):
        zone_ids = by_level[level]
        sample = risks[zone_ids[0]]
        info = _sub(alert, "info")
        _sub(info, "language", "en-IN")
        _sub(info, "category", "Met")
        _sub(info, "event", "Extreme Heat" if level in ("Orange", "Red") else "Heat Advisory")
        _sub(info, "responseType", "Prepare")
        _sub(info, "urgency", CAP_URGENCY[level])
        _sub(info, "severity", CAP_SEVERITY[level])
        _sub(info, "certainty", "Likely")  # a modelled score, never "Observed"
        _sub(info, "onset", day_start.isoformat(timespec="seconds"))
        _sub(info, "expires", day_end.isoformat(timespec="seconds"))
        _sub(info, "senderName", "HeatLens (demo)")
        _sub(info, "headline", f"{level} heat alert - {city.name}, {date}")
        _sub(info, "description", f"{cap_description(sample)} Applies to {len(zone_ids)} zone(s).")
        _sub(
            info,
            "instruction",
            " ".join(f"[{a.department}] {a.title}." for a in hap.actions_for(level)),
        )
        for name, value in (
            ("HeatLens:hap_level", level),
            ("HeatLens:calibrated_score", f"{sample.calibrated_score:.1f}"),
            ("HeatLens:risk_band", sample.risk_band),
            ("HeatLens:relative_risk", f"{sample.health.relative_risk:.3f}"),
            ("HeatLens:mri_0_100", f"{sample.health.mri_0_100:.1f}"),
            ("HeatLens:calibration_status", sample.health.calibration_status),
        ):
            param = _sub(info, "parameter")
            _sub(param, "valueName", name)
            _sub(param, "value", value)
        for zid in zone_ids:
            area = _sub(info, "area")
            _sub(area, "areaDesc", risks[zid].name)
            _sub(area, "polygon", _polygon_text(zid))
            geocode = _sub(area, "geocode")
            _sub(geocode, "valueName", "H3")
            _sub(geocode, "value", zid)

    ET.indent(alert)
    return '<?xml version="1.0" encoding="UTF-8"?>\n' + ET.tostring(alert, encoding="unicode")


def webhook_preview(req: WebhookRequest, ctx: DayContext | None = None) -> WebhookPreview:
    """The JSON a department's system WOULD receive. Nothing is sent."""
    resp = triggers(req.city, req.date, ctx)
    floor = hap.level_rank(req.min_level)

    items = []
    for group in resp.groups:
        if hap.level_rank(group.level) < floor:
            continue
        mine = [a.model_dump() for a in group.actions if a.department == req.department]
        if mine:
            items.append({"level": group.level, "zone_ids": group.zone_ids, "actions": mine})

    return WebhookPreview(
        delivery=WebhookDelivery(),
        payload={
            "event": "heatlens.heat_action_trigger",
            "schema_version": "1.0",
            "department": req.department,
            "city": req.city,
            "date": req.date,
            "source": resp.source,
            "issued_at": resp.issued_at,
            "level_basis": resp.level_basis,
            "calibration_status": resp.calibration_status,
            "triggers": items,
        },
    )
