/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Meta */
        get: operations["get_meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cities */
        get: operations["list_cities_api_v1_cities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cities/{city_id}/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get City Zones */
        get: operations["get_city_zones_api_v1_cities__city_id__zones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Risk Zones */
        get: operations["get_risk_zones_api_v1_risk_zones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/zones/{zone_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Zone Detail */
        get: operations["get_zone_detail_api_v1_risk_zones__zone_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forecast/{city_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get City Forecast */
        get: operations["get_city_forecast_api_v1_forecast__city_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forecast/{city_id}/hourly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get City Hourly
         * @description One day hour by hour, for the dashboard's exposure chart and peak danger period.
         */
        get: operations["get_city_hourly_api_v1_forecast__city_id__hourly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/advisory/{zone_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Zone Advisory */
        get: operations["get_zone_advisory_api_v1_advisory__zone_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dispatch/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Dispatch Preview */
        post: operations["post_dispatch_preview_api_v1_dispatch_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/triggers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Triggers */
        get: operations["get_triggers_api_v1_alerts_triggers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/cap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cap Feed */
        get: operations["get_cap_feed_api_v1_alerts_cap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/webhook-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Webhook Preview */
        post: operations["post_webhook_preview_api_v1_alerts_webhook_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/validation/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Validation Status */
        get: operations["get_validation_status_api_v1_validation_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/validation/evidence-ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evidence Ledger */
        get: operations["get_evidence_ledger_api_v1_validation_evidence_ledger_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdvisoryResponse */
        AdvisoryResponse: {
            /** Zone Id */
            zone_id: string;
            /** Date */
            date: string;
            /**
             * Source
             * @enum {string}
             */
            source: "history" | "forecast";
            /** Persona */
            persona: string;
            /** Risk Band */
            risk_band: string;
            /** Regime */
            regime: string;
            /** Recommendations */
            recommendations: components["schemas"]["Recommendation"][];
            /**
             * Hap Trigger
             * @enum {string}
             */
            hap_trigger: "Green" | "Yellow" | "Orange" | "Red";
            /** Hap Trigger Basis */
            hap_trigger_basis: string;
            health: components["schemas"]["HealthRisk"];
            cap_preview: components["schemas"]["CapPreview"];
        };
        /**
         * Benchmark
         * @description Parsed from results/benchmark_report.md, the repo's own structural benchmark.
         */
        Benchmark: {
            /** Scope */
            scope: string;
            /** Tables */
            tables: components["schemas"]["BenchmarkTable"][];
            /** Limitations */
            limitations: string[];
        };
        /** BenchmarkTable */
        BenchmarkTable: {
            /** Key */
            key: string;
            /** Title */
            title: string;
            /** Columns */
            columns: string[];
            /** Rows */
            rows: {
                [key: string]: number | string;
            }[];
        };
        /** CapPreview */
        CapPreview: {
            /** Identifier */
            identifier: string;
            /** Sender */
            sender: string;
            /** Sent */
            sent: string;
            /**
             * Status
             * @enum {string}
             */
            status: "Actual" | "Exercise" | "System" | "Test" | "Draft";
            /**
             * Msg Type
             * @enum {string}
             */
            msg_type: "Alert" | "Update" | "Cancel";
            /**
             * Scope
             * @enum {string}
             */
            scope: "Public" | "Restricted" | "Private";
            /**
             * Category
             * @constant
             */
            category: "Met";
            /** Event */
            event: string;
            /**
             * Urgency
             * @enum {string}
             */
            urgency: "Immediate" | "Expected" | "Future" | "Past" | "Unknown";
            /**
             * Severity
             * @enum {string}
             */
            severity: "Extreme" | "Severe" | "Moderate" | "Minor" | "Unknown";
            /**
             * Certainty
             * @enum {string}
             */
            certainty: "Observed" | "Likely" | "Possible" | "Unlikely" | "Unknown";
            /** Headline */
            headline: string;
            /** Description */
            description: string;
            /** Area Desc */
            area_desc: string;
        };
        /** CityInfo */
        CityInfo: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Tz */
            tz: string;
            /** Zone Count */
            zone_count: number;
            date_range: components["schemas"]["DateRange"];
        };
        /**
         * CrossCheck
         * @description An independent absolute-threshold effect from a *different* city and a
         *     weaker (descriptive) study design. Informational only — never folded into
         *     ``relative_risk`` (datasets/health/exposure_response_india.json says to use
         *     it "only as a cross-check").
         */
        CrossCheck: {
            /** Condition */
            condition: string;
            /** Triggered */
            triggered: boolean;
            /** Effect Pct */
            effect_pct: number;
            /** Source */
            source: string;
        };
        /** DateRange */
        DateRange: {
            /** Start */
            start: string;
            /** End */
            end: string;
        };
        /**
         * DebtSnapshot
         * @description Stage 5, Plan C. Already computed in results/ahmedabad_daily_2010_2024.csv —
         *     this schema is a pass-through, not new science.
         */
        DebtSnapshot: {
            evidence: components["schemas"]["EvidenceLabel"];
            /** Debt Worker */
            debt_worker: number | null;
            /** Debt Elderly */
            debt_elderly: number | null;
            /** Carry */
            carry: number | null;
            /** Worker Hours Rectal Ge Limit */
            worker_hours_rectal_ge_limit: number | null;
            /** Iso7933 In Range Frac */
            iso7933_in_range_frac: number | null;
        };
        /** DispatchRequest */
        DispatchRequest: {
            /** Zone Id */
            zone_id: string;
            /**
             * Channel
             * @enum {string}
             */
            channel: "sms" | "whatsapp";
            /**
             * Language
             * @enum {string}
             */
            language: "en" | "hi" | "gu";
            /**
             * Persona
             * @enum {string}
             */
            persona: "construction" | "elderly" | "general";
            /** Date */
            date?: string | null;
        };
        /**
         * DispatchResponse
         * @description §5.6: status is hard-coded SIMULATED — there is no code path that can
         *     return anything else until a real gateway is wired (Open Decision, not yet
         *     scheduled). A demo cannot accidentally imply a message was sent.
         */
        DispatchResponse: {
            /**
             * Status
             * @default SIMULATED
             * @constant
             */
            status: "SIMULATED";
            /**
             * Gateway
             * @default not_configured
             * @constant
             */
            gateway: "not_configured";
            /**
             * Disclaimer
             * @default No message was sent. Gateway integration pending authorisation.
             */
            disclaimer: string;
            /** Recipients Estimated */
            recipients_estimated: number | null;
            /** Recipients Basis */
            recipients_basis: string;
            /** Message Preview */
            message_preview: string;
        };
        /**
         * EvidenceLabel
         * @enum {string}
         */
        EvidenceLabel: "MEASURED_POINT" | "MEASURED_CENSUS" | "MEASURED_FORECAST" | "MODELLED_PUBLISHED" | "MODELLED_UNCALIBRATED" | "MODELLED_CALIBRATED" | "MEASURED_SATELLITE" | "ILLUSTRATIVE";
        /** EvidenceLedger */
        EvidenceLedger: {
            /** Entries */
            entries: components["schemas"]["LedgerEntry"][];
        };
        /** ForecastDay */
        ForecastDay: {
            /** Lead Day */
            lead_day: number;
            /** Date */
            date: string;
            /** Ta Max C */
            ta_max_c: number | null;
            /** Wbgt Max C */
            wbgt_max_c: number | null;
            /** Utci Max C */
            utci_max_c: number | null;
            /** Night Min Ta C */
            night_min_ta_c: number | null;
            /** Thermal Stress */
            thermal_stress: string | null;
            /**
             * Calibrated Score
             * @description HeatLens composite thermal-stress score, 0-100: a regime-weighted combination of UTCI, WBGT, dry-heat excess and heat debt. Its meaning in deaths is calibrated on one event - the 31 days of the May 2010 Ahmedabad heatwave (backend/scripts/calibrate_score.py): see ``score_mortality`` and /api/v1/validation/status. Its internal weights and band cut-offs are still hand-set.
             */
            calibrated_score: number;
            /** Risk Band */
            risk_band: string;
            /** Regime */
            regime: string;
            /** Dominant Driver */
            dominant_driver: string;
            /** Component Breakdown */
            component_breakdown: {
                [key: string]: number;
            };
            health: components["schemas"]["HealthRisk"];
            /** Hap Level */
            hap_level?: ("Green" | "Yellow" | "Orange" | "Red") | null;
            /** Hap Basis */
            hap_basis?: string | null;
            score_mortality?: components["schemas"]["ScoreMortality"] | null;
        };
        /** ForecastResponse */
        ForecastResponse: {
            evidence: components["schemas"]["EvidenceLabel"];
            /** City */
            city: string;
            /** Zone Id */
            zone_id: string | null;
            /** Issued At */
            issued_at: string;
            /** Issue Date */
            issue_date: string;
            /** Source */
            source: string;
            /** Days */
            days: components["schemas"]["ForecastDay"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HapAction */
        HapAction: {
            /** Action Id */
            action_id: string;
            /**
             * Department
             * @enum {string}
             */
            department: "public" | "municipal" | "health" | "labour" | "power_utility";
            /** Kind */
            kind: string;
            /** Title */
            title: string;
            /** Detail */
            detail: string;
            /** Basis */
            basis: string;
        };
        /**
         * HealthModelInfo
         * @description How the health layer is built and how well this data reproduces the
         *     source study's own exposure definition — served on the Methods page.
         */
        HealthModelInfo: {
            evidence: components["schemas"]["EvidenceLabel"];
            /** Definition */
            definition: string;
            /** Threshold P97 C */
            threshold_p97_c: number;
            /** Threshold Basis */
            threshold_basis: string;
            /** Base Effect Pct */
            base_effect_pct: number;
            /** Base Ci Pct */
            base_ci_pct: [
                number,
                number
            ];
            /** Intensity Slope Pct Per Pct */
            intensity_slope_pct_per_pct: number;
            /** Intensity Slope Ci */
            intensity_slope_ci: [
                number,
                number
            ];
            /** Intensity Centre Pct */
            intensity_centre_pct: number;
            /** Mri Definition */
            mri_definition: string;
            /** Reference Stats */
            reference_stats: components["schemas"]["ReferenceStat"][];
            /** Deviations */
            deviations: string[];
            /** Not Modelled */
            not_modelled: string[];
            /** Citation */
            citation: string;
        };
        /**
         * HealthRisk
         * @description Mortality risk for one date, from a published exposure-response model.
         *
         *     ``relative_risk`` is a ratio against non-heatwave days of the same city —
         *     the comparison the source study makes — not a forecast of deaths. It is
         *     exactly 1.0 outside a published heatwave, because that is what the
         *     study's reference group means, not because heat is harmless there.
         *     ``calibration_status`` is a Literal with one value on purpose: there is no
         *     code path that can claim local validation.
         */
        HealthRisk: {
            evidence: components["schemas"]["EvidenceLabel"];
            /**
             * Exposure Tier
             * @enum {string}
             */
            exposure_tier: "heatwave" | "single_day_above_p97" | "below_threshold";
            /** Daily Mean Temp C */
            daily_mean_temp_c: number;
            /** Threshold P97 C */
            threshold_p97_c: number;
            /** Intensity Pct */
            intensity_pct: number | null;
            /** Relative Risk */
            relative_risk: number;
            /** Rr Ci Low */
            rr_ci_low: number;
            /** Rr Ci High */
            rr_ci_high: number;
            /** Mri 0 100 */
            mri_0_100: number;
            /**
             * Calibration Status
             * @default not_validated_locally
             * @constant
             */
            calibration_status: "not_validated_locally";
            /** Source */
            source: string;
            /** Cross Checks */
            cross_checks: components["schemas"]["CrossCheck"][];
        };
        /** HourlyPoint */
        HourlyPoint: {
            /** Hour */
            hour: number;
            /** Ta C */
            ta_c: number | null;
            /** Heat Index C */
            heat_index_c: number | null;
            /** Wbgt C */
            wbgt_c: number | null;
            /** Utci C */
            utci_c: number | null;
            /** Utci Category */
            utci_category: string | null;
        };
        /**
         * HourlyResponse
         * @description One day hour by hour (services/hourly.py). City-level: the same for every ward.
         */
        HourlyResponse: {
            evidence: components["schemas"]["EvidenceLabel"];
            /** City */
            city: string;
            /** Date */
            date: string;
            /** Source */
            source: string;
            /** Points */
            points: components["schemas"]["HourlyPoint"][];
            /** Peak Start Hour */
            peak_start_hour: number | null;
            /** Peak End Hour */
            peak_end_hour: number | null;
            /** Peak Rule */
            peak_rule: string;
            /** Max Utci C */
            max_utci_c: number | null;
            /** Max Ta C */
            max_ta_c: number | null;
            /** Min Ta C */
            min_ta_c: number | null;
            /** Max Heat Index C */
            max_heat_index_c: number | null;
            /** Daytime Cloud Cover Pct */
            daytime_cloud_cover_pct: number | null;
            /** Basis */
            basis: string;
        };
        /**
         * LandCover
         * @description What the ward's ground is made of (ESA WorldCover 2021, 10 m), with the city average and
         *     how strongly each land type goes with ground temperature across the 48 wards (Pearson r).
         *     services/explain.py uses this to say, in plain words, why a ward runs hot or cool.
         */
        LandCover: {
            evidence: components["schemas"]["EvidenceLabel"];
            /** Built Up Pct */
            built_up_pct: number;
            /** Trees Pct */
            trees_pct: number;
            /** Grass Shrub Pct */
            grass_shrub_pct: number;
            /** Cropland Pct */
            cropland_pct: number;
            /** Bare Pct */
            bare_pct: number;
            /** Water Pct */
            water_pct: number;
            /** City Built Up Pct */
            city_built_up_pct: number;
            /** City Trees Pct */
            city_trees_pct: number;
            /** City Cropland Pct */
            city_cropland_pct: number;
            /** City Water Pct */
            city_water_pct: number;
            /** R Built Up Night */
            r_built_up_night: number;
            /** R Trees Day */
            r_trees_day: number;
            /** R Trees Night */
            r_trees_night: number;
            /** R Cropland Night */
            r_cropland_night: number;
            /** R Water Day */
            r_water_day: number;
            /** Basis */
            basis: string;
        };
        /** LedgerEntry */
        LedgerEntry: {
            /** Component */
            component: string;
            /**
             * Status
             * @enum {string}
             */
            status: "MEASURED_POINT" | "MEASURED_CENSUS" | "MEASURED_FORECAST" | "MEASURED_GEODATA" | "MEASURED_SATELLITE" | "MODELLED_PUBLISHED" | "MODELLED_UNCALIBRATED" | "MODELLED_CALIBRATED" | "ILLUSTRATIVE" | "NOT_AVAILABLE";
            /** Basis */
            basis: string;
            /** Note */
            note: string;
            /** Title */
            title?: string | null;
            /**
             * Code
             * @default []
             */
            code: string[];
        };
        /** OutcomeValidation */
        OutcomeValidation: {
            /**
             * Status
             * @enum {string}
             */
            status: "not_run" | "completed";
            /** Data Source */
            data_source: string | null;
            /** Evidence Status */
            evidence_status: string | null;
            /** Report */
            report: {
                [key: string]: unknown;
            } | null;
            /** How To Run */
            how_to_run: string;
        };
        /** Recommendation */
        Recommendation: {
            /** Kind */
            kind: string;
            /** Title */
            title: string;
            /** Rationale */
            rationale: string;
            /** Basis */
            basis: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "low" | "moderate" | "high";
        };
        /** ReferenceStat */
        ReferenceStat: {
            /** Name */
            name: string;
            /** Published */
            published: number | null;
            /** Reproduced */
            reproduced: number;
            /** Unit */
            unit: string;
        };
        /**
         * RiskZonesResponse
         * @description GET /risk/zones — IMPLEMENTATION_PLAN.md §5.2.
         *
         *     The weather input is one city-level point (measured 2026-09-22: 48 ward centroids
         *     resolve to 8 Open-Meteo model cells, Tmax spread 0.3-1.3 C — services/spatial.py's
         *     COVERAGE_NOTE), so thermal fields and scores are the same for every ward. What differs
         *     between wards is measured: ``surface_temperature`` (MODIS) and ``exposure``
         *     (population).
         *
         *     ``source`` says whether ``date`` was served from the 2010-2024 record or the
         *     live forecast; ``issued_at`` is set only for the latter.
         */
        RiskZonesResponse: {
            evidence: components["schemas"]["EvidenceLabel"];
            /** City */
            city: string;
            /** Date */
            date: string;
            /**
             * Source
             * @enum {string}
             */
            source: "history" | "forecast";
            /** Issued At */
            issued_at: string | null;
            /** Zone Count */
            zone_count: number;
            /** Coverage Note */
            coverage_note: string;
            /** Zones */
            zones: components["schemas"]["ZoneRisk"][];
        };
        /**
         * ScoreMortality
         * @description What a HeatLens score meant in deaths in May 2010 (services/score_calibration.py): deaths as a
         *     multiple of a normal May day, with a 95 % bootstrap interval. Only inside the range of scores seen
         *     that month; outside it the ratio fields are None and ``in_calibrated_range`` is False.
         */
        ScoreMortality: {
            evidence: components["schemas"]["EvidenceLabel"];
            /** In Calibrated Range */
            in_calibrated_range: boolean;
            /** Death Ratio */
            death_ratio: number | null;
            /** Ci Low */
            ci_low: number | null;
            /** Ci High */
            ci_high: number | null;
            /** Calibrated Range */
            calibrated_range: [
                number,
                number
            ];
            /** Basis */
            basis: string;
        };
        /**
         * StationVerification
         * @description backend/scripts/build_station_verification.py: HeatLens's temperature inputs against the
         *     Ahmedabad airport station (NOAA GSOD).
         */
        StationVerification: {
            /** Station Name */
            station_name: string;
            /** Source */
            source: string;
            /** Season */
            season: string;
            /** Retrieved */
            retrieved: string;
            /** Caveats */
            caveats: string[];
            /** History Model */
            history_model: string;
            history: components["schemas"]["VerificationScore"];
            /** Forecast Model */
            forecast_model: string;
            /** Forecast Leads */
            forecast_leads: {
                [key: string]: components["schemas"]["VerificationScore"];
            };
        };
        /**
         * SurfaceTemperature
         * @description This ward's own measured MODIS land-surface temperature (backend/scripts/
         *     build_lst_offsets.py), day and night, as a seasonal March-June mean and as an anomaly
         *     against the city mean. Surface skin temperature, not 2 m air temperature: it is shown as
         *     what it is and is not converted into air temperature, WBGT, UTCI or score.
         *     ``pixel_rule`` says whether the value averages pixels centred inside the ward
         *     ("centre_inside") or, for a ward smaller than a pixel, every pixel it overlaps
         *     ("all_touched").
         */
        SurfaceTemperature: {
            evidence: components["schemas"]["EvidenceLabel"];
            /** Lst Day C */
            lst_day_c: number;
            /** Lst Day Anomaly C */
            lst_day_anomaly_c: number;
            /** Lst Night C */
            lst_night_c: number;
            /** Lst Night Anomaly C */
            lst_night_anomaly_c: number;
            /**
             * Pixel Rule
             * @enum {string}
             */
            pixel_rule: "centre_inside" | "all_touched";
            /** Basis */
            basis: string;
        };
        /**
         * ThermalSnapshot
         * @description One day's worth of headline thermal indices for a location. All measured
         *     or published-standard values — WBGT/UTCI/Heat Index are validated
         *     international standards, not HeatLens's own uncalibrated composites.
         */
        ThermalSnapshot: {
            /** Ta Max C */
            ta_max_c: number | null;
            /** Wbgt Max C */
            wbgt_max_c: number | null;
            /** Utci Max C */
            utci_max_c: number | null;
            /** Night Min Ta C */
            night_min_ta_c: number | null;
        };
        /**
         * TriggerGroup
         * @description All zones that share one level on the requested date.
         *
         *     Grouped rather than listed per zone because every zone currently shares one
         *     weather point (services/spatial.py COVERAGE_NOTE), so a per-zone list would
         *     repeat the same object 127 times. The shape is unchanged once zones diverge:
         *     there would simply be more than one group.
         */
        TriggerGroup: {
            /**
             * Level
             * @enum {string}
             */
            level: "Green" | "Yellow" | "Orange" | "Red";
            /** Zone Ids */
            zone_ids: string[];
            /** Actions */
            actions: components["schemas"]["HapAction"][];
        };
        /** TriggersResponse */
        TriggersResponse: {
            /**
             * Status
             * @default DRY_RUN
             * @constant
             */
            status: "DRY_RUN";
            /** City */
            city: string;
            /** Date */
            date: string;
            /**
             * Source
             * @enum {string}
             */
            source: "history" | "forecast";
            /** Issued At */
            issued_at: string | null;
            /** Level Basis */
            level_basis: string;
            /** City Ta Max C */
            city_ta_max_c?: number | null;
            /** City Ta Max Source */
            city_ta_max_source?: string | null;
            /**
             * Calibration Status
             * @default not_validated_locally
             * @constant
             */
            calibration_status: "not_validated_locally";
            /** Groups */
            groups: components["schemas"]["TriggerGroup"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValidationStatus */
        ValidationStatus: {
            /** Index Calibrated Against Health Outcomes */
            index_calibrated_against_health_outcomes: boolean;
            /** Reason */
            reason: string;
            /** What Was Tested */
            what_was_tested: string[];
            /** What Was Not Tested */
            what_was_not_tested: string[];
            benchmark: components["schemas"]["Benchmark"];
            health_model: components["schemas"]["HealthModelInfo"];
            outcome_validation: components["schemas"]["OutcomeValidation"];
            station_verification: components["schemas"]["StationVerification"] | null;
            /** Score Calibration */
            score_calibration?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * VerificationScore
         * @description Model daily max temperature minus the station's, over March-June days both have.
         */
        VerificationScore: {
            /** N Days */
            n_days: number;
            /** Bias C */
            bias_c: number;
            /** Mae C */
            mae_c: number;
            /** Rmse C */
            rmse_c: number;
            /** Pearson R */
            pearson_r: number;
            /** Amc Level Agreement Pct */
            amc_level_agreement_pct: number;
            /** Station Alert Days */
            station_alert_days: number;
            /** Station Alert Days Model Missed */
            station_alert_days_model_missed: number;
        };
        /** VersionInfo */
        VersionInfo: {
            /** Version */
            version: string;
            /** Data As Of */
            data_as_of: string;
            /** Calibration Status */
            calibration_status: string;
            /** Cities */
            cities: number;
            /** Zones */
            zones: number;
        };
        /** WebhookDelivery */
        WebhookDelivery: {
            /**
             * Status
             * @default SIMULATED
             * @constant
             */
            status: "SIMULATED";
            /** Target Url */
            target_url?: null;
            /**
             * Note
             * @default No HTTP request was made. Webhook endpoints for this department are not configured.
             */
            note: string;
        };
        /**
         * WebhookPreview
         * @description What WOULD be POSTed to a department's system, and nothing more.
         */
        WebhookPreview: {
            delivery: components["schemas"]["WebhookDelivery"];
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
        };
        /** WebhookRequest */
        WebhookRequest: {
            /**
             * Department
             * @enum {string}
             */
            department: "public" | "municipal" | "health" | "labour" | "power_utility";
            /** Date */
            date: string;
            /**
             * City
             * @default ahmedabad
             */
            city: string;
            /**
             * Min Level
             * @default Yellow
             * @enum {string}
             */
            min_level: "Green" | "Yellow" | "Orange" | "Red";
        };
        /**
         * ZoneDetailResponse
         * @description GET /risk/zones/{zone_id} — IMPLEMENTATION_PLAN.md §5.3.
         */
        ZoneDetailResponse: {
            /**
             * Source
             * @enum {string}
             */
            source: "history" | "forecast";
            zone: components["schemas"]["ZoneRisk"];
            /** History */
            history: components["schemas"]["ZoneHistoryPoint"][];
            debt: components["schemas"]["DebtSnapshot"];
        };
        /**
         * ZoneExposure
         * @description Stage 4. ``evidence`` covers the elderly share (Census 2011 C-13, Ahmedabad
         *     district urban — real, but one figure for every ward). Population is a different
         *     kind of number (a published gridded model, JRC GHS-POP), so it carries its own
         *     ``population_evidence``; both are None only if the ward file hasn't been built.
         *     See services/exposure.py.
         */
        ZoneExposure: {
            evidence: components["schemas"]["EvidenceLabel"];
            /** Population Count */
            population_count: number | null;
            /** Population Density Per Km2 */
            population_density_per_km2?: number | null;
            population_evidence?: components["schemas"]["EvidenceLabel"] | null;
            /** Population Status */
            population_status: string;
            /** Elderly Share Pct */
            elderly_share_pct: number;
            /** Elderly Share Geography */
            elderly_share_geography: string;
            /**
             * Elderly Share Basis
             * @default
             */
            elderly_share_basis: string;
        };
        /**
         * ZoneHistoryPoint
         * @description One day of the city-level trend shown on a zone's page (the same series for every
         *     ward - services/spatial.py). No evidence field of its own: the zone's ``ZoneRisk``
         *     carries the labels for the fields it shares with this point.
         */
        ZoneHistoryPoint: {
            /** Date */
            date: string;
            /** Calibrated Score */
            calibrated_score: number;
            /** Risk Band */
            risk_band: string;
            /** Phd */
            phd: number | null;
            /** Night Min Ta C */
            night_min_ta_c: number | null;
            /** Wbgt Max C */
            wbgt_max_c: number | null;
        };
        /**
         * ZoneRisk
         * @description One zone, one date. The Stage 6 ensemble output plus its Stage 2/4 inputs.
         *
         *     ``thermal``, ``calibrated_score``, ``risk_band`` and ``component_breakdown`` are the
         *     city's own values, the same for every ward (services/spatial.py). What is specific to
         *     the ward is ``surface_temperature`` (measured) and ``exposure`` (population).
         */
        ZoneRisk: {
            evidence: components["schemas"]["EvidenceLabel"];
            /** Zone Id */
            zone_id: string;
            /** Name */
            name: string;
            /**
             * Calibrated Score
             * @description HeatLens composite thermal-stress score, 0-100: a regime-weighted combination of UTCI, WBGT, dry-heat excess and heat debt. Its meaning in deaths is calibrated on one event - the 31 days of the May 2010 Ahmedabad heatwave (backend/scripts/calibrate_score.py): see ``score_mortality`` and /api/v1/validation/status. Its internal weights and band cut-offs are still hand-set.
             */
            calibrated_score: number;
            /** Risk Band */
            risk_band: string;
            /** Regime */
            regime: string;
            /** Dominant Driver */
            dominant_driver: string;
            /** Component Breakdown */
            component_breakdown: {
                [key: string]: number;
            };
            thermal: components["schemas"]["ThermalSnapshot"];
            exposure: components["schemas"]["ZoneExposure"];
            health: components["schemas"]["HealthRisk"];
            surface_temperature?: components["schemas"]["SurfaceTemperature"] | null;
            land_cover?: components["schemas"]["LandCover"] | null;
            /** Why Hot */
            why_hot?: string[];
            /**
             * Weather Basis
             * @default
             */
            weather_basis: string;
            score_mortality?: components["schemas"]["ScoreMortality"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionInfo"];
                };
            };
        };
    };
    list_cities_api_v1_cities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CityInfo"][];
                };
            };
        };
    };
    get_city_zones_api_v1_cities__city_id__zones_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                city_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_risk_zones_api_v1_risk_zones_get: {
        parameters: {
            query: {
                /** @description YYYY-MM-DD: a historical date, or one in the live forecast window */
                date: string;
                city?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskZonesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_zone_detail_api_v1_risk_zones__zone_id__get: {
        parameters: {
            query: {
                /** @description YYYY-MM-DD */
                date: string;
                history_days?: number;
                city?: string;
            };
            header?: never;
            path: {
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_city_forecast_api_v1_forecast__city_id__get: {
        parameters: {
            query?: {
                zone_id?: string | null;
                days?: number;
            };
            header?: never;
            path: {
                city_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_city_hourly_api_v1_forecast__city_id__hourly_get: {
        parameters: {
            query: {
                /** @description YYYY-MM-DD */
                date: string;
            };
            header?: never;
            path: {
                city_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HourlyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_zone_advisory_api_v1_advisory__zone_id__get: {
        parameters: {
            query: {
                date: string;
                persona?: string;
                city?: string;
            };
            header?: never;
            path: {
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdvisoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_dispatch_preview_api_v1_dispatch_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DispatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DispatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_triggers_api_v1_alerts_triggers_get: {
        parameters: {
            query: {
                /** @description YYYY-MM-DD: historical or in the live forecast window */
                date: string;
                city?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cap_feed_api_v1_alerts_cap_get: {
        parameters: {
            query: {
                date: string;
                city?: string;
                min_level?: "Green" | "Yellow" | "Orange" | "Red";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CAP 1.2 alert (status Draft) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/cap+xml": unknown;
                };
            };
            /** @description No zone at or above min_level on this date */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_webhook_preview_api_v1_alerts_webhook_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_validation_status_api_v1_validation_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationStatus"];
                };
            };
        };
    };
    get_evidence_ledger_api_v1_validation_evidence_ledger_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceLedger"];
                };
            };
        };
    };
}
